### ISSUE TITLE
Blum Point not increasing.

### ISSUE THREAD

**Issue by uniqueunique7x7** [NabiKAZ/Blum-Scripts#1]
Points not increasing at all, i asked a guy who succeeded on making this work and i share this script asking fix, he says payload data is missing and there is problem with execution process.
Can u please recheck it all again ?? Would be helpful for mamy people

**Comment by NabiKAZ** [comment]
Yes, I am aware of the problem and the reason for sharing this script is to solve this problem. As I clearly explained the issue in Readme here:
https://github.com/NabiKAZ/Blum-Scripts?tab=readme-ov-file#a-big-or-maybe-small-but-important-problem

**Comment by hanguyxn** [comment]
> Yes, I am aware of the problem and the reason for sharing this script is to solve this problem. As I clearly explained the issue in Readme here: https://github.com/NabiKAZ/Blum-Scripts?tab=readme-ov-file#a-big-or-maybe-small-but-important-problem

Oh i saw this solution encode payload work but max 280 point

**Comment by hanguyxn** [comment]
![Uploading Screenshot 2024-10-25 055235.png…]()

**Comment by NabiKAZ** [comment]
Are you sure it works? Because my example is set for 50 points, but it doesn't work.
Also, your screenshot is not loaded.

**Comment by NabiKAZ** [comment]
Fixed.
