### ISSUE TITLE
Error come from wasm

### ISSUE THREAD

**Issue by anhduca4** [NabiKAZ/Blum-Scripts#2]
When I run it it show error 
```
RuntimeError: unreachable
    at wasm://wasm/000dd44e:wasm-function[151]:0x2955e
    at wasm://wasm/000dd44e:wasm-function[198]:0x2b16f
    at wasm://wasm/000dd44e:wasm-function[84]:0x1abaa
```
How to fix it ?
I used node: 20

**Comment by NabiKAZ** [comment]
I test with node v20.18.0 and there is no problem.
Make sure you clone the project correctly and all files are intact.
Try to test again with the same version of node.
